version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  pactify:
    image: haha0224/pactify:latest
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/Pactify

  tester:
    image: alpine:latest
    depends_on:
      - pactify
    entrypoint: ["sh", "-c", "apk add --no-cache curl && sleep 60 && curl -f http://pactify:5000 || true"]